// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArCBeLizgjHI4fEzpujz0cFevUvP3K8Hs',
    appId: '1:354163585499:web:ed18afcde52af3579237fe',
    messagingSenderId: '354163585499',
    projectId: 'inclass15-4f4a2',
    authDomain: 'inclass15-4f4a2.firebaseapp.com',
    storageBucket: 'inclass15-4f4a2.firebasestorage.app',
    measurementId: 'G-EW585N9MEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0DtRF6edt1w0xpg1JRg0B3xOqIOk9K-o',
    appId: '1:354163585499:android:ae40edd5da40af4a9237fe',
    messagingSenderId: '354163585499',
    projectId: 'inclass15-4f4a2',
    storageBucket: 'inclass15-4f4a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOLesRxcDP5t3XOZuF7jPtNdRrEWguF2c',
    appId: '1:354163585499:ios:ed4af5bb45f964559237fe',
    messagingSenderId: '354163585499',
    projectId: 'inclass15-4f4a2',
    storageBucket: 'inclass15-4f4a2.firebasestorage.app',
    iosBundleId: 'com.example.inclass15',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOLesRxcDP5t3XOZuF7jPtNdRrEWguF2c',
    appId: '1:354163585499:ios:ed4af5bb45f964559237fe',
    messagingSenderId: '354163585499',
    projectId: 'inclass15-4f4a2',
    storageBucket: 'inclass15-4f4a2.firebasestorage.app',
    iosBundleId: 'com.example.inclass15',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArCBeLizgjHI4fEzpujz0cFevUvP3K8Hs',
    appId: '1:354163585499:web:769c0f6b77c1a4ab9237fe',
    messagingSenderId: '354163585499',
    projectId: 'inclass15-4f4a2',
    authDomain: 'inclass15-4f4a2.firebaseapp.com',
    storageBucket: 'inclass15-4f4a2.firebasestorage.app',
    measurementId: 'G-1LES1T95Z0',
  );

}